name: AlchemistMMExtension
main: me.bedwarshurts.mmextension.AlchemistMMExtension
version: 1.0
api-version: 1.21
description: An extension for MythicMobs
author: bedwarshurts
depend: [MythicMobs,PlaceholderAPI]