name: AlchemistMMExtension
main: me.bedwarshurts.mmextension.AlchemistMMExtension
version: 2.0.2
api-version: 1.21
description: An extension for MythicMobs
author: bedwarshurts
depend: [MythicMobs,PlaceholderAPI,ProtocolLib]