name: AlchemistMMExtension
main: me.bedwarshurts.mmextension.AlchemistMMExtension
version: 1.2.2
api-version: 1.21
description: An extension for MythicMobs
author: bedwarshurts
depend: [MythicMobs,PlaceholderAPI,ProtocolLib]