name: AlchemistMMExtension
main: me.bedwarshurts.mmextension.AlchemistMMExtension
version: 2.2.1
api-version: 1.21
description: An extension for MythicMobs
author: bedwarshurts
depend: [MythicMobs,PlaceholderAPI,ProtocolLib]
softdepend: [MythicLib,MMOCore]